// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZJjd2S0qJg5hhjfZFV6Eme9HwLX1Eaw',
    appId: '1:502641517459:web:38c412144a258f48303e66',
    messagingSenderId: '502641517459',
    projectId: 'quotebook-c323b',
    authDomain: 'quotebook-c323b.firebaseapp.com',
    storageBucket: 'quotebook-c323b.firebasestorage.app',
    measurementId: 'G-8W4MPR01B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAn0bnQ_8kidrzHDznmwXd2UBFRNTQA_0',
    appId: '1:502641517459:android:b283958aa1419929303e66',
    messagingSenderId: '502641517459',
    projectId: 'quotebook-c323b',
    storageBucket: 'quotebook-c323b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV9WHltmeXbwNHttcmSmRVtHjovermZCM',
    appId: '1:502641517459:ios:5cb6f05b5b746c8f303e66',
    messagingSenderId: '502641517459',
    projectId: 'quotebook-c323b',
    storageBucket: 'quotebook-c323b.firebasestorage.app',
    iosBundleId: 'com.example.quotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV9WHltmeXbwNHttcmSmRVtHjovermZCM',
    appId: '1:502641517459:ios:5cb6f05b5b746c8f303e66',
    messagingSenderId: '502641517459',
    projectId: 'quotebook-c323b',
    storageBucket: 'quotebook-c323b.firebasestorage.app',
    iosBundleId: 'com.example.quotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZJjd2S0qJg5hhjfZFV6Eme9HwLX1Eaw',
    appId: '1:502641517459:web:5bad56d3bb0c4b63303e66',
    messagingSenderId: '502641517459',
    projectId: 'quotebook-c323b',
    authDomain: 'quotebook-c323b.firebaseapp.com',
    storageBucket: 'quotebook-c323b.firebasestorage.app',
    measurementId: 'G-7B4TC1GHM6',
  );
}
